# Generated by Django 2.1.5 on 2019-02-06 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_driver', models.BooleanField(default=False)),
                ('plate_number', models.CharField(max_length=8)),
                ('vehicle_type', models.CharField(default='', max_length=100)),
                ('max_passengers', models.IntegerField(default=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(default='', max_length=100)),
                ('rider_name', models.CharField(default='', max_length=100)),
                ('destination', models.CharField(default='', max_length=100)),
                ('expected_arrival', models.DateTimeField(default=django.utils.timezone.now)),
                ('passenger_number', models.IntegerField(default='1')),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=100)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('isComplete', models.BooleanField(default=False)),
                ('can_Share', models.BooleanField(default=False)),
                ('special_request', models.CharField(blank=True, default='', max_length=100)),
                ('ride_owner', models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
