# Generated by Django 2.1.5 on 2019-02-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uberuser',
            old_name='driver',
            new_name='is_driver',
        ),
    ]
