# Generated by Django 2.1.5 on 2019-02-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0002_auto_20190206_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rides',
            old_name='can_Share',
            new_name='isShare',
        ),
    ]
