# Generated by Django 2.1.5 on 2019-02-04 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uber', '0004_auto_20190203_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(default='', max_length=100)),
                ('expected_arrival', models.DateTimeField(default=django.utils.timezone.now)),
                ('passenger_number', models.IntegerField(default='1')),
                ('vehicle_type', models.CharField(default='', max_length=100)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('isComplete', models.BooleanField(default=False)),
                ('is_driver', models.BooleanField(default=False)),
                ('can_Share', models.BooleanField(default=False)),
                ('pick_vehicle_plate', models.CharField(max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
