# Generated by Django 2.1.5 on 2019-02-06 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uber', '0004_auto_20190206_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='ride_sharer',
            field=models.ManyToManyField(default=None, related_name='share_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
